// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjdafebctoioqwqolhjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqZGFmZWJjdG9pb3F3cW9saGprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMxNjE3OTYsImV4cCI6MjA0ODczNzc5Nn0.GZmMBWO1iWTy-k4kGkRQ79D06G6Iq7gjXNM451iRJVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);